if (instance_exists(Obj_prota)){
	Obj_prota.persistent = true;
}
//MUITO IMPORTANTE - ATIVAR PERSISTENT NAS PROPRIEDADES DA ROOM
//SE N QUANDO DER PAUSE ELA N VAI VOLTAR DE ONDE PAROU ANTES DO PAUSE